### ISSUE TITLE
如果源码不放在网站根目录，怎么配置路径呢？

### ISSUE THREAD

**Issue by wang191X** [jockchou/gitblog#1]
比如我依次点击“首页”->“GitBlog安装”，网址会跳转到http://localhost/blog/gitblog/install.html，无法找到页面，实际上源码路径在"http://localhost/gitblog-2.0.2/"下面，改成"http://localhost/gitblog-2.0.2/index.php/blog/gitblog/install.html"，能够成功跳转。
虽然可以，岂不是每次都得改，太麻烦了，还是应该怎么弄~

**Comment by jockchou** [comment]
请把网站根目录配置到gitblog目录。
例如你的安装包解压到gitblog-2.0.2/目录，请把这个目录配置成网站根目录。如果是apache，可以配置一个虚拟目录到这个目录。
这是必须的。

具体请参照官方文档：http://gitblogdoc.sinaapp.com/blog/gitblog/apache.html
