### ISSUE TITLE
markdown和latex解析混淆

### ISSUE THREAD

**Issue by cherichy** [jockchou/gitblog#11]
在博客里面写latex公式的时候，latex公式里面会有很多下划线，而md解析的时候把下划线全解析成了<em>，具体样子可以看我的gitblog。
今天刚建起来，觉得很不错，但是这个问题希望改进。可以参考这个网站
https://stackedit.io/
还有我的博客，可以看到问题。[cherichy's blog](http://cherichy.sinaapp.com/blog/%25E5%25A0%2586%25EF%25BC%2588heap%25EF%25BC%2589%25E7%25AC%2594%25E8%25AE%25B0.html)

**Comment by cherichy** [comment]
经过一番摸索，发现需要在latex公式里面对下划线转义，这样还是很麻烦，希望能给出更好的解决方法。
ps：我博客里面试验性的文章里面的latex公式已经修正。

**Comment by jockchou** [comment]
Markdown 使用星号（*）和底线（_）作为标记强调字词的符号，被 \* 或 _ 包围的字词会被转成用 <em> 标签包围，用两个 \* 或 _ 包起来的话，则会被转成 <strong>，例如：

_single asterisks_

_single underscores_

**double asterisks**

**double underscores**
会转成：

<em>single asterisks</em>

<em>single underscores</em>

<strong>double asterisks</strong>

<strong>double underscores</strong>
你可以随便用你喜欢的样式，唯一的限制是，你用什么符号开启标签，就要用什么符号结束。

强调也可以直接插在文字中间：

un_frigging_believable
但是如果你的 \* 和 _ 两边都有空白的话，它们就只会被当成普通的符号。

如果要在文字前后直接插入普通的星号或底线，你可以用反斜线：

*this text is surrounded by literal asterisks*
