### ISSUE TITLE
博文排序的问题

### ISSUE THREAD

**Issue by liyu34** [jockchou/gitblog#2]
我昨天写了两篇博文，一篇就像是被置顶了一样，今天写的新博文也在它下面，不知道这是怎么回事，我尝试了改名，改时间，改文件名，改summary等方式都不行，昨天写的那篇还是依然置顶。

**Comment by jockchou** [comment]
尝试先清一下缓存
然后把博客的date调到最近的一天

博客是按date属性排序的
如果date一样，是按更新时间
