### ISSUE TITLE
目录建议

### ISSUE THREAD

**Issue by qingliangcn** [jockchou/gitblog#3]
把img目录和posts目录放在一个目录(如data)下，便于统一管理，例如使用一个git仓库，现在这种方式相当要麻烦些（目前我采用软连接的方式指向了同一个目录）。或者采用可配置的方式去设定目录

**Comment by liyu34** [comment]
你好，请问你是使用Git来发布博文的吗？

**Comment by jockchou** [comment]
我已经意识到这个问题了，感谢你的建议，下版本改进！

**Comment by jockchou** [comment]
这样做也有一个缺点，图片如果不放到gitblog的目录中，就无法直接访问到了。比如你的网站是app.gitblog.com。你把数据都放到/data/下面，gitblog会从这里读取markdown，但是图片也在这里的话，代理服务器nginx已经访问不到这里的图片了。

**Comment by qingliangcn** [comment]
是否能访问取决于方案选择：
1. 对于站点来说，一定会有一个访问根目录【并非源码根目录】，例如www
2. 数据(md+图片)放在同一个A目录，同访问目录分离
3. 不论A目录在哪里，最终的数据都生成到www下

#### 如果A目录不可访问，则需要间接访问图片

a. 从A拷贝到www【最简单，但是浪费空间】
b. www软链接一个目录到A目录【脚本来做】

#### 如果A目录可以访问，则直接访问图片

a. 直接读取【扫描md时记录好路径关系】

建议可以做到：
1. 用户的md和图片在一个文件夹下如何存放不做限制，是否有子目录都可以
2. 用户的同步只需要同步数据目录，其他文件直接在服务器上可以覆盖升级

**Comment by qingliangcn** [comment]
/data/这样的根目录的确不太合适，建议是这样：

-ROOT
---| frameworks    框架和库
---| apps               具体的逻辑
---| www               静态目录
---| data                原始数据文件

# 

域名目录指向www

**Comment by jockchou** [comment]
当然，如果是自己搭建一个网站，你这样的考虑是合理的。但是作为一个简单的博客系统，
估计你这样分下来，安装配置就过于麻烦了，很多人就搞不清楚了。
我已经在2.2版本里，把图片和markdown文件统一归到一个目录下管理了，应该是比较方便了。

**Comment by qingliangcn** [comment]
附加一个初始化脚本即可，不必让用户觉得麻烦
