### ISSUE TITLE
about commit 02220ce

### ISSUE THREAD

**Issue by vc12345679** [jockchou/gitblog#32]
今天看一下了 ckeyer@02220ce  ，[Parsedown.php](https://github.com/erusev/parsedown) 的作者在扩展项目 [ParsedownExtra.php](https://github.com/erusev/parsedown-extra) 中提供了类似的功能[[1]](https://michelf.ca/projects/php-markdown/extra/#spe-attr)，如果直接使用 ParsedownExtra.php，可以免去维护 gitblog 项目中对 Parsedown.php 的手动修改，@jockchou @ckeyer 觉得可行吗？

**Comment by ckeyer** [comment]
非常好 @vc12345679

**Comment by vc12345679** [comment]
测试ParsedownExtra新功能可用，包括
- Inline HTML
- Markdown Inside HTML Blocks
- Special Attributes
- Fenced Code Blocks
- Tables
- Definition Lists
- Footnotes
- Output
- Abbreviations
- Ordered Lists
- Emphasis
- Backslash Escapes

其中**Special Attributes**可代替 02220ce
