### ISSUE TITLE
一个配置项无效和归档日期问题

### ISSUE THREAD

**Issue by similarJ** [jockchou/gitblog#33]
首先非常感谢作者开发了这套系统。
在我的使用过程中有一些小的问题(我使用的是quest主题)，conf.yml中avatar是否是用户头像的意思呢，我在自己的[个人博客](http://leslin.cn)中配置了，无效，是还没有开发完嘛?

在按日期归档的的右侧栏(详情可以查看我的博客)中日期没有按照先后顺序排列，我检查了我写的几篇博客的日期，都是采用2016-08-12这样8个数字的日期格式。是否还有其他需要注意的地方呢？

**Comment by vc12345679** [comment]
代作者回答第一个问题，是否显示头像，在什么位置显示，显示成多大，都是由主题控制的。

搜了一下，目前只在cube主题的主页和line主题的404页显示，具体见
- theme/cube/_include/header.html, line 6-7
- theme/line/404.html, line 7-8

另外在 defalut quest 的css里也预定义了 avatar 的样式，估计作者后面会添加。

**Comment by vc12345679** [comment]
第二个问题已提交修复

**Comment by similarJ** [comment]
非常感谢
