### ISSUE TITLE
归档和标签连接页面Oops! 404.

### ISSUE THREAD

**Issue by similarJ** [jockchou/gitblog#37]
见[博客](http://leslin.cn)。很奇怪，这种现象应该是模板生成时解析错误吧。

**Comment by vc12345679** [comment]
用的不是最新版本吧？中间有一个版本确实写错了，检查一下 app/libraries/Markdown.php，
670行附近，把
`"url" => ... "$type/" . $tag . ".html" ...`
 改成
 `"url" => ... "$type/" . $id . ".html" ...`
再清一下缓存。当然，更新到最新版本最方便。
