### ISSUE TITLE
文件名不支持中文？

### ISSUE THREAD

**Issue by hjb2722404** [jockchou/gitblog#38]
markdown文件名为汉字的时候，访问文章详情就报404，文件名该问英文，就正常了

**Comment by vc12345679** [comment]
locale en_US.UTF-8 的服务器上测试markdown文件名使用中文访问正常

**Comment by vc12345679** [comment]
问题已在releases v2.2 或更新版本中解决，更新一下就好了
> [2.修复markdown文件名为特殊符号时的bug](https://github.com/jockchou/gitblog/releases/tag/v2.2)
