### ISSUE TITLE
[TOC]不能正常显示

### ISSUE THREAD

**Issue by keman1984** [jockchou/gitblog#4]
我试用的是2.2版，发现markdown转换成HTML的时候，有些是出不来的。比如[TOC]。是否考虑更新markdown转换程序

**Comment by jockchou** [comment]
markdown标准之外还有很多语法，各家各不相同，不同的编辑器也有不同的实现，总之很复杂。
不会考虑更换markdown解析器，倒是会考虑内置多种解析器，可以让用户自己选择解析器。
