### ISSUE TITLE
分页错误

### ISSUE THREAD

**Issue by qingchuwudi** [jockchou/gitblog#41]
比如我的某个首页：
`https://xxx.xxx.com/category/1155787600.html`
里面有5页，我点第2页的时候，链接中有一部分路径重复了：
`https://xxx.xxx.com/category/category/1155787600/page/2.html`

**删掉一个 “category/”恢复正常**

某个分类下面的分页：
`https://xxx.xxx.com/category/1155787600/page/category/1155787600/page/2.html`
正常：
`https://xxx.xxx.com/category/1155787600/page/2.html`

主题使用**default**

**Comment by vc12345679** [comment]
这样应该能解决问题了 #42
