### ISSUE TITLE
blog文件夹下的子文件夹名字不支持中文

### ISSUE THREAD

**Issue by Druson** [jockchou/gitblog#50]
blog文件夹下创建名字包含中文的文件夹， 访问里面的markdown文件返回错误: 

```
Oops! 404.

您访问的页面不存在了，你可以试试查看下面的内容.
```

使用环境是nginx + php-fpm, 操作系统是linux (debian).

**Comment by vc12345679** [comment]
问题出在 app/libraries/Markdown.php 内 urlencodeFileName() 函数未对文件夹名进行 URL 编码，已在 39a9d00 中修复该 bug。
