### ISSUE TITLE
font.useso.com 访问很慢

### ISSUE THREAD

**Issue by san-chang** [jockchou/gitblog#51]
![em _2017410102414](https://cloud.githubusercontent.com/assets/13452500/24843700/d304b0fa-1d94-11e7-82a2-79f64a37de2a.png)
![em _201741010237](https://cloud.githubusercontent.com/assets/13452500/24843701/d3efab8c-1d94-11e7-8483-a153e3652f8b.png)
ping 正常，但是访问出现502， 使用的地址是http://www.gitblog.cn/index.html  中引用的fonts.useso.com的地址：
![cddb52c2-9228-4492-8e35-3b10dd1da413](https://cloud.githubusercontent.com/assets/13452500/24843732/086d478e-1d95-11e7-986e-f53c6ad7ce8a.jpg)
是否需要更换字体cdn或者不用？

**Comment by vc12345679** [comment]
去年11月之后的版本中已修复文档地址和字体问题
