### ISSUE TITLE
gitblog不支持PHP7

### ISSUE THREAD

**Issue by AleutianXie** [jockchou/gitblog#53]
现gitblog内置的CI和Parsedown插件不支持PHP7。 我简单的升级了下CI和Parsedown,可以兼容PHP7了

另：
Markdown.php 中 line 483
$ctime = date("Y-m-d H:i:s", $fileProp['cdate']);

cdate在Markdown中不存在，导致PHP报错

**Comment by vc12345679** [comment]
请更新新版，Parsedown和Parsedown-Extra已在 021bf84 （Nov 15, 2016）中更新以支持php7。
并已亲测验证，验证环境：
```
$ php --version
PHP 7.1.3 (cli) (built: Mar 17 2017 16:59:59) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
$ nginx -v
nginx version: nginx/1.10.3
```
PS 当前版本中，`$ctime = date("Y-m-d H:i:s", $fileProp['cdate']);`在Markdown.php[第533行](https://github.com/jockchou/gitblog/blob/master/app/libraries/Markdown.php#L533)。

**Comment by AleutianXie** [comment]
@vc12345679 谢谢。奇怪，我是git clone的master分支，不知道为什么没有这个改动……，不过我自己更新了CI和Parsedown。

**Comment by vc12345679** [comment]
你试试 git fetch？ 再 git status 看一下

**Comment by AleutianXie** [comment]
@vc12345679 git log 看了下，最近的commit 还是14年的，可能是我git clone的时候出什么问题了。这个问题忽略吧。
另那个‘cdate’的问题，是对应的md文件没有相应cdate的属性，PHP报错。

**Comment by vc12345679** [comment]
@AleutianXie git remote -v 看一下对应的origin远程库URL，是`https://github.com/jockchou/gitblog.git`吗？
cdate是在 [sys/helpers/file_helper.php](https://github.com/jockchou/gitblog/blob/master/sys/helpers/file_helper.php#L306) 里定义的，赋值在[第306行](https://github.com/jockchou/gitblog/blob/master/sys/helpers/file_helper.php#L306)

**Comment by vc12345679** [comment]
@AleutianXie 知道git不工作的原因了，Jul 31, 2015 之后jockchou把项目整个升级到v2.0了，跟之前版本不兼容，github上的repository也是推倒重来的，Initial Commit (jockchou committed on Jul 21, 2015, 87d0885)

**Comment by AleutianXie** [comment]
@vc12345679 哦，好的。谢谢，我重新git clone了一下，更新到最新了
