### ISSUE TITLE
对md文件进行增删改后，手动清空cache，刷新才生效

### ISSUE THREAD

**Issue by tom2015git** [jockchou/gitblog#6]
感觉这种操作太麻烦，能进行优化吗？现在的定位是写日志的人操作不频繁，但是像我这种类型的操作就比较频繁
再就是能否增加，直接在网页上编辑md文件，那样就更方便了

**Comment by jockchou** [comment]
1.你可能关闭缓存功能
2.或者你可以使用脚本监控blog目录是否变化
3.下版本会考虑在url后加个参数nocache，让系统强制刷新缓存的这么个功能，方便用户调试页面

做在线编，需要登录流程，而且在线编辑器做起来有点麻烦，也不是非常强烈的需求。
由于目前就我一个人在维护这个项目，工作比较忙，所以目前不会考虑做这个。

还有其他更重要的功能在版本计划中，等用的人多了再考虑。
